import{a as L,S as U,i as c}from"./assets/vendor-r3ybvNbe.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();L.defaults.baseURL="https://pixabay.com/api/";let y=1;async function w(s,e={}){const o={key:"49206664-0ec6b9af3cdb6ffe721ed5088",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:y,...e};try{const a=await L.get("",{params:o});return y+=1,a.data}catch(a){throw console.error("Error fetching data from Pixabay API:",a),a}}function M(){y=1}let N=new U(".gallery a",{captions:!0,captionsData:"alt",captionType:"attr",captionDelay:250,animationSpeed:350,captionPosition:"bottom"});function S(){N.refresh()}function E(s){console.log("Дані для рендерингу:",s);const e=document.querySelector(".gallery"),o=s.map(a=>{const{webformatURL:t,largeImageURL:r,likes:i,views:I,tags:P,comments:q,downloads:x}=a,u=document.createElement("li");u.classList.add("gallery-item");const g=document.createElement("a");g.classList.add("gallery-link"),g.href=r;const n=document.createElement("img");n.classList.add("gallery-image"),n.src=t,n.alt=P,n.width=360,n.height=200,u.appendChild(g),g.appendChild(n);const h=document.createElement("div");return h.classList.add("gallery-item-info"),h.innerHTML=`
  <div class="item-info-container">
    <span class="description-name">Likes</span>
    <span class="description-counts">${i}</span>
  </div>
  <div class="item-info-container">
    <span class="description-name">Views</span>
    <span class="description-counts">${I}</span>
  </div>
  <div class="item-info-container">
    <span class="description-name">Comments</span>
    <span class="description-counts">${q}</span>
  </div>
  <div class="item-info-container">
    <span class="description-name">Downloads</span>
    <span class="description-counts">${x}</span>
  </div>
`,u.appendChild(h),u});e.append(...o)}function O(){const s=document.querySelector(".gallery");s.innerHTML=""}const b="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEYSURBVHgBrZZRDoIwDIYrwfDqTeQo3ohxEr0BXsW77GXFOFdkYcC6DuFPCJB1/7fCWgBgZEzfIPY256BYzqfkzE8nUNbCE+DzgqSKK8W6OVBV5xYk+ZUbgw/IFMVKmfxtng3ZYy5CjjBnISlzrXUtGcZiZpDxolsGIWItvTi/OK0xAuk7GhsBRjEGioNMmffMXKNEAAeRzENACYJc8QxF5IuJNBZhS2PSfBGwhNB9rjmpgHxZ5jqprAyC3jT0mi29RwSE5v6xhO9EhAjblN0tqS38G59t02ShKeCzU2Kh+SDE9z0GAUGxGPKaLS4F2aqVudcRENb8CIhovgeSMl/VwdQWbOPOl5yPvivs25b2MWjKJOu3hTX+AgZ5PpvL0NSkAAAAAElFTkSuQmCC",C=document.querySelector(".form"),p=document.querySelector(".loader"),v=document.querySelector(".gallery"),d=document.querySelector(".load-more"),f={message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",iconUrl:b},R={message:"We're sorry, but you've reached the end of search results.",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",iconUrl:b};let A=0,l=0,m="";C.addEventListener("submit",D);d.addEventListener("click",G);async function D(s){if(s.preventDefault(),m=s.currentTarget.elements.searchQuery.value.trim(),!!m){p.classList.remove("visually-hidden"),O(),C.reset(),M(),l=0;try{const e=await w(m);if(!e||!e.hits||e.hits.length===0){c.show(f),d.classList.add("visually-hidden");return}const o=e.hits;A=e.totalHits,l=o.length,E(o),S(),B(l,A)}catch(e){c.show({...f,message:`An error occurred: ${e.message}`})}finally{p.classList.add("visually-hidden")}}}async function G(){p.classList.remove("visually-hidden");const s=v.scrollHeight;try{const e=await w(m);if(!e||!e.hits||e.hits.length===0){c.show(f),d.classList.add("visually-hidden");return}const o=e.hits;l+=o.length,E(o),S();const a=v.scrollHeight;window.scrollBy({top:a-s,behavior:"smooth"}),B(l,A)}catch(e){c.show({...f,message:`An error occurred: ${e.message}`})}finally{p.classList.add("visually-hidden")}}function B(s,e){s>=e?(c.show(R),d.classList.add("visually-hidden")):d.classList.remove("visually-hidden")}
//# sourceMappingURL=index.js.map
